// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf91SoQGgerkFaitWFoEtwqHc6MMKNaE8',
    appId: '1:206627570023:web:1da229a1e1dee099912fc2',
    messagingSenderId: '206627570023',
    projectId: 'ibites-69340',
    authDomain: 'ibites-69340.firebaseapp.com',
    storageBucket: 'ibites-69340.firebasestorage.app',
    measurementId: 'G-W700WR59VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAudC-u2RI7EV1oWr8r7wDkJw7RQ8F_Bk',
    appId: '1:206627570023:android:368961b5ba1ba3b8912fc2',
    messagingSenderId: '206627570023',
    projectId: 'ibites-69340',
    storageBucket: 'ibites-69340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArmpgBc69RV6y_K2xVhuuNbQX-VrLWRp0',
    appId: '1:206627570023:ios:06f9d383803f838e912fc2',
    messagingSenderId: '206627570023',
    projectId: 'ibites-69340',
    storageBucket: 'ibites-69340.firebasestorage.app',
    iosBundleId: 'com.example.ibites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArmpgBc69RV6y_K2xVhuuNbQX-VrLWRp0',
    appId: '1:206627570023:ios:06f9d383803f838e912fc2',
    messagingSenderId: '206627570023',
    projectId: 'ibites-69340',
    storageBucket: 'ibites-69340.firebasestorage.app',
    iosBundleId: 'com.example.ibites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf91SoQGgerkFaitWFoEtwqHc6MMKNaE8',
    appId: '1:206627570023:web:58ae7f754ed31335912fc2',
    messagingSenderId: '206627570023',
    projectId: 'ibites-69340',
    authDomain: 'ibites-69340.firebaseapp.com',
    storageBucket: 'ibites-69340.firebasestorage.app',
    measurementId: 'G-5950MZTKRH',
  );
}
